version: 2

jobs:
  "build":
    docker: &DOCKERIMAGE
      - image: jenkinsrise/cci-v2-docker-java8-gcloud:0.0.1
    working_directory: ~/storage-gcs-logging
    
    steps:
      - checkout
      - restore_cache:
          key: storage-gcs-logging-{{ checksum "pom.xml" }}
      - run: if find src/main |grep /queue.xml; then exit 1; fi    
      - run:
          name: Copy private keys
          command: |
            git clone git@github.com:Rise-Vision/private-keys.git
            mkdir -p src/private-keys
            cp private-keys/storage-server/* src/private-keys
            mkdir -p WEB-INF/classes
            cp src/private-keys/* WEB-INF/classes
      - run: mvn dependency:go-offline -s settings.xml
      - run: if [[ ! -e src/private-keys/rvaserver2-7ab43ba8bac3.p12 ]]; then exit 1; fi
      - run: if [[ ! -e src/log-schemas/cloud_storage_storage_schema_v0.json ]]; then exit 1; fi
      - run: if [[ ! -e src/log-schemas/cloud_storage_usage_schema_v0.json ]]; then exit 1; fi
      - run: if find src/main |grep /queue.xml; then exit 1; fi
      - save_cache:
          paths:
            - ~/.m2
          key: storage-gcs-logging-{{ checksum "pom.xml" }}
            
  "deploy_stage":
    docker: *DOCKERIMAGE
    working_directory: ~/storage-gcs-logging
    steps:
      - checkout
      - restore_cache:
          key: storage-gcs-logging-{{ checksum "pom.xml" }}
      - run:
          name: Copy private keys
          command: |
            git clone git@github.com:Rise-Vision/private-keys.git
            mkdir -p src/private-keys
            cp private-keys/storage-server/* src/private-keys
            mkdir -p WEB-INF/classes
            cp src/private-keys/* WEB-INF/classes
      - run:
          name: Authenticate with GCloud
          command: |    
            echo $ACCT_AUTH_STAGE | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
            sudo gcloud --quiet components update
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud config set project $PROJECT_ID_STAGE 
      - run:
          name: Deploy
          command: |
            mvn clean
            mvn appengine:deploy -s settings.xml -Dapp.deploy.version=$(echo -n $CIRCLE_BRANCH |awk 'BEGIN{FS="/"}{print tolower($NF)}') -Dapp.deploy.promote=false -Dapp.deploy.project=rvacore-test -P test
          
  "deploy_prod":
    docker: *DOCKERIMAGE
    working_directory: ~/storage-gcs-logging
    steps:
      - checkout
      - restore_cache:
          key: storage-gcs-logging-{{ checksum "pom.xml" }}
      - run:
          name: Copy private keys
          command: |
            git clone git@github.com:Rise-Vision/private-keys.git
            mkdir -p src/private-keys
            cp private-keys/storage-server/* src/private-keys
            mkdir -p WEB-INF/classes
            cp src/private-keys/* WEB-INF/classes
      - run:
          name: Authenticate with GCloud
          command: |    
            echo $ACCT_AUTH | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
            sudo gcloud --quiet components update
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud config set project $PROJECT_ID  
      - run:
          name: Deploy
          command: |
            mvn clean
            mvn appengine:deploy -s settings.xml -Dapp.deploy.version=r$(echo -n $((CIRCLE_BUILD_NUM%10))) -Dapp.deploy.promote=true -Dapp.deploy.project=rvaserver2 -P prod

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - "build"
      - "deploy_stage":
          requires:
            - build
          filters:
            branches:
              ignore:
                - master

      - "deploy_prod":
          requires:
            - build
          filters:
            branches:
              only:
                - master